// audit (API.md, 3.6; ARCHITECTURE.md, 11).
import { z } from 'zod';
import { Instant, PageQuery, Uuid } from './common.js';

export const ACTOR_TYPES = ['USER', 'SYSTEM', 'NODE'] as const;
export type ActorType = (typeof ACTOR_TYPES)[number];

export const AuditLogsQuery = PageQuery.extend({
  entityType: z.string().max(60).optional(),
  entityId: Uuid.optional(),
  actorUserId: Uuid.optional(),
  action: z.string().max(100).optional(),
  competitionId: Uuid.optional(),
  from: Instant.optional(),
  to: Instant.optional(),
});
export type AuditLogsQuery = z.infer<typeof AuditLogsQuery>;

export interface AuditEntry {
  id: string;
  occurredAt: string;
  actor: { type: ActorType; userId: string | null; displayName: string | null; nodeId: string | null };
  action: string;
  entityType: string;
  entityId: string | null;
  before: Record<string, unknown> | null;
  after: Record<string, unknown> | null;
  reason: string | null;
  ipMasked: string | null;
  traceId: string | null;
  platformIntervention: boolean;
}

/** Каталог действий аудита Phase 2. Новые действия добавляются сюда вместе с кодом, который их пишет. */
export const AUDIT_ACTIONS = [
  'auth.login',
  'auth.login_failed_admin',
  'auth.password_changed',
  'auth.password_reset',
  'auth.totp_enabled',
  'auth.totp_disabled',
  'auth.refresh_reuse_detected',
  'user.registered',
  'user.email_verified',
  'user.updated',
  'user.blocked',
  'user.unblocked',
  'user.platform_role_granted',
  'user.platform_role_revoked',
  'person.upserted',
  'organization.created',
  'organization.updated',
  'organization.status_changed',
  'organization.member_invited',
  'organization.member_joined',
  'organization.member_updated',
  'file.uploaded',
  'dictionary.upserted',
  'setting.updated',
  'athlete.created',
  'athlete.updated',
  'athlete.archived',
  'athlete.membership_added',
  'athlete.membership_ended',
  'athlete.coach_linked',
  'athlete.coach_unlinked',
  'athlete.rank_added',
  'athlete.rank_revoked',
  'athlete.merged',
  'athlete.import_created',
  'athlete.import_committed',
  'coach.created',
  'coach.updated',
  'coach.membership_added',
  'coach.membership_ended',
  'referee.created',
  'referee.updated',
  'guardian.added',
  'guardian.verified',
  'guardian.ended',
  'guardian.invited',
  'guardian.linked',
  'consent_template.created',
  'consent_template.updated',
  'consent_template.published',
  'consent.given',
  'consent.revoked',
  'ruleset.created',
  'ruleset.version_created',
  'ruleset.version_updated',
  'ruleset.version_published',
  'age_group.created',
  'age_group.updated',
  'age_group.deleted',
  'weight_category.created',
  'weight_category.updated',
  'weight_category.deleted',
  'category_template.created',
  'category_template.updated',
  'category_template.deleted',
  'document.uploaded',
  'document.status_changed',
  'document.deleted',
  'document.expired',
  'venue.created',
  'venue.updated',
  'competition.created',
  'competition.updated',
  'competition.deleted',
  'competition.status_changed',
  'competition.regulation_updated',
  'competition.requirements_updated',
  'competition.category_rules_updated',
  'competition.member_invited',
  'competition.member_joined',
  'competition.member_updated',
  'category.created',
  'category.updated',
  'category.deleted',
  'category.generated',
  'category.status_changed',
  'category.merged',
  'application.created',
  'application.updated',
  'application.status_changed',
  'entry.created',
  'entry.deleted',
  'entry.snapshot_refreshed',
  'entry.decided',
  'entry.withdrawn',
  'entry.transferred',
  'entry.exported',
  'admission.check_waived',
  'checkin.updated',
  'scale.created',
  'scale.updated',
  'scale.deleted',
  'weigh_in_window.created',
  'weigh_in_window.updated',
  'weigh_in_window.deleted',
  'weigh_in.recorded',
  'medical.clearance_recorded',
  'medical.clearance_revoked',
  'draw.created',
  'draw.published',
  'draw.superseded',
  'bracket.advanced',
  'mat.created',
  'mat.updated',
  'session.created',
  'session.updated',
  'schedule.generated',
  'schedule.items_moved',
  'schedule.published',
  'mat_assignment.updated',
  'mat_assignment.copied',
  // Phase 7a — схватки: переходы, результат, подтверждение, неявки (события счёта — в журнале схватки, не в аудите).
  'match.called',
  'match.call_cancelled',
  'match.started',
  'match.paused',
  'match.resumed',
  'match.result_recorded',
  'match.result_corrected',
  'match.result_confirmed',
  'match.no_show',
  'match.no_show_auto',
  // Phase 7b — итоги: изменение результата, перенос и отмена, ручная схватка, врач, итоги категории.
  'match.result_amended',
  'match.postponed',
  'match.unpostponed',
  'match.cancelled',
  'match.created',
  'medical.incident_recorded',
  'category.results_computed',
  'category.results_published',
  'category.results_amended',
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];
