-- Миграция данных, сгенерирована scripts/generate-data-migration.ts. Идемпотентна. Не править вручную.

-- Каталог permissions (packages/contracts/src/permissions.ts)
INSERT INTO "permission" ("code", "module", "description", "scopes") VALUES
  ('platform.settings.manage', 'platform', 'Системные настройки', ARRAY['PLATFORM']::"RoleScope"[]),
  ('user.view', 'user', 'Просмотр пользователей', ARRAY['PLATFORM']::"RoleScope"[]),
  ('user.manage', 'user', 'Блокировка и разблокировка пользователей', ARRAY['PLATFORM']::"RoleScope"[]),
  ('role.manage', 'role', 'Назначение и снятие платформенных ролей', ARRAY['PLATFORM']::"RoleScope"[]),
  ('dictionary.manage', 'dictionary', 'Справочники', ARRAY['PLATFORM']::"RoleScope"[]),
  ('consent_template.manage', 'consent_template', 'Тексты согласий', ARRAY['PLATFORM']::"RoleScope"[]),
  ('athlete.merge', 'athlete', 'Слияние дублей спортсменов', ARRAY['PLATFORM']::"RoleScope"[]),
  ('audit.view', 'audit', 'Журнал аудита', ARRAY['PLATFORM', 'COMPETITION']::"RoleScope"[]),
  ('organization.approve', 'organization', 'Активация и приостановка организаций', ARRAY['PLATFORM', 'ORGANIZATION']::"RoleScope"[]),
  ('organization.create_child', 'organization', 'Создание дочерней организации', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('organization.update', 'organization', 'Изменение данных организации', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('organization.members.view', 'organization', 'Просмотр участников организации', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('organization.members.manage', 'organization', 'Приглашение и исключение участников', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('athlete.view', 'athlete', 'Просмотр спортсменов организации', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('athlete.create', 'athlete', 'Создание спортсмена', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('athlete.update', 'athlete', 'Изменение спортсмена', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('athlete.archive', 'athlete', 'Архивирование спортсмена', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('athlete.import', 'athlete', 'Импорт спортсменов из файла', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('guardian.manage', 'guardian', 'Законные представители спортсмена', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('consent.record', 'consent', 'Внесение бумажного согласия (скан)', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('coach.manage', 'coach', 'Тренеры организации', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('referee.manage', 'referee', 'Судьи и судейские категории', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('document.upload', 'document', 'Загрузка документов спортсмена', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('document.view', 'document', 'Просмотр документов', ARRAY['ORGANIZATION', 'COMPETITION']::"RoleScope"[]),
  ('document.verify', 'document', 'Проверка документов', ARRAY['COMPETITION']::"RoleScope"[]),
  ('category.manage', 'category', 'Возрастные группы, весовые категории, шаблоны', ARRAY['PLATFORM', 'ORGANIZATION']::"RoleScope"[]),
  ('ruleset.manage', 'ruleset', 'Наборы правил и их версии', ARRAY['PLATFORM', 'ORGANIZATION']::"RoleScope"[]),
  ('venue.manage', 'venue', 'Места проведения', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('competition.create', 'competition', 'Создание турнира от имени организации', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('registration.create', 'registration', 'Подача заявок от имени организации', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('ranking.manage', 'ranking', 'Рейтинговые системы', ARRAY['ORGANIZATION']::"RoleScope"[]),
  ('competition.view', 'competition', 'Служебные данные турнира', ARRAY['COMPETITION']::"RoleScope"[]),
  ('competition.update', 'competition', 'Изменение турнира и положения', ARRAY['COMPETITION']::"RoleScope"[]),
  ('competition.delete', 'competition', 'Удаление черновика турнира', ARRAY['COMPETITION']::"RoleScope"[]),
  ('competition.publish', 'competition', 'Публикация турнира', ARRAY['COMPETITION']::"RoleScope"[]),
  ('competition.transition', 'competition', 'Переходы статуса турнира', ARRAY['COMPETITION']::"RoleScope"[]),
  ('competition.members.manage', 'competition', 'Персонал турнира', ARRAY['COMPETITION']::"RoleScope"[]),
  ('competition_category.manage', 'competition_category', 'Категории турнира, правила, требования', ARRAY['COMPETITION']::"RoleScope"[]),
  ('category.merge', 'category', 'Объединение категорий', ARRAY['COMPETITION']::"RoleScope"[]),
  ('registration.view', 'registration', 'Все заявки турнира', ARRAY['COMPETITION']::"RoleScope"[]),
  ('registration.approve', 'registration', 'Одобрение участия', ARRAY['COMPETITION']::"RoleScope"[]),
  ('registration.reject', 'registration', 'Отклонение участия', ARRAY['COMPETITION']::"RoleScope"[]),
  ('registration.return', 'registration', 'Возврат заявки на исправление', ARRAY['COMPETITION']::"RoleScope"[]),
  ('registration.export', 'registration', 'Выгрузка списка заявок', ARRAY['COMPETITION']::"RoleScope"[]),
  ('entry.withdraw', 'entry', 'Снятие участника', ARRAY['COMPETITION']::"RoleScope"[]),
  ('entry.transfer', 'entry', 'Перевод участника в другую категорию', ARRAY['COMPETITION']::"RoleScope"[]),
  ('admission.view', 'admission', 'Статусы допуска', ARRAY['COMPETITION']::"RoleScope"[]),
  ('admission.override', 'admission', 'Исключение из проверки допуска', ARRAY['COMPETITION']::"RoleScope"[]),
  ('checkin.view', 'checkin', 'Статусы прибытия', ARRAY['COMPETITION']::"RoleScope"[]),
  ('checkin.perform', 'checkin', 'Отметка прибытия', ARRAY['COMPETITION']::"RoleScope"[]),
  ('weighin.manage', 'weighin', 'Весы и окна взвешивания', ARRAY['COMPETITION']::"RoleScope"[]),
  ('weighin.record', 'weighin', 'Запись взвешивания', ARRAY['COMPETITION']::"RoleScope"[]),
  ('weighin.view', 'weighin', 'Результаты взвешивания', ARRAY['COMPETITION']::"RoleScope"[]),
  ('medical.view', 'medical', 'Медицинские допуски и инциденты', ARRAY['COMPETITION']::"RoleScope"[]),
  ('medical.record', 'medical', 'Запись медицинского допуска и инцидента', ARRAY['COMPETITION']::"RoleScope"[]),
  ('draw.create', 'draw', 'Черновик жеребьёвки', ARRAY['COMPETITION']::"RoleScope"[]),
  ('draw.publish', 'draw', 'Публикация жеребьёвки', ARRAY['COMPETITION']::"RoleScope"[]),
  ('draw.republish', 'draw', 'Новая версия опубликованной жеребьёвки', ARRAY['COMPETITION']::"RoleScope"[]),
  ('mat.manage', 'mat', 'Ковры', ARRAY['COMPETITION']::"RoleScope"[]),
  ('schedule.manage', 'schedule', 'Сессии и расписание', ARRAY['COMPETITION']::"RoleScope"[]),
  ('schedule.publish', 'schedule', 'Публикация расписания', ARRAY['COMPETITION']::"RoleScope"[]),
  ('mat_assignment.manage', 'mat_assignment', 'Назначение бригад', ARRAY['COMPETITION']::"RoleScope"[]),
  ('match.create', 'match', 'Ручное создание схватки', ARRAY['COMPETITION']::"RoleScope"[]),
  ('match.update', 'match', 'Вызов, пауза, перенос схватки', ARRAY['COMPETITION']::"RoleScope"[]),
  ('match.start', 'match', 'Старт схватки', ARRAY['COMPETITION']::"RoleScope"[]),
  ('match.finish', 'match', 'Завершение схватки', ARRAY['COMPETITION']::"RoleScope"[]),
  ('match.cancel', 'match', 'Отмена схватки', ARRAY['COMPETITION']::"RoleScope"[]),
  ('scoring.create', 'scoring', 'Запись событий схватки', ARRAY['COMPETITION']::"RoleScope"[]),
  ('scoring.update', 'scoring', 'Аннулирование событий схватки', ARRAY['COMPETITION']::"RoleScope"[]),
  ('result.confirm', 'result', 'Подтверждение результата схватки', ARRAY['COMPETITION']::"RoleScope"[]),
  ('result.amend', 'result', 'Изменение подтверждённого результата', ARRAY['COMPETITION']::"RoleScope"[]),
  ('result.publish', 'result', 'Публикация результатов категории', ARRAY['COMPETITION']::"RoleScope"[]),
  ('team_standing.publish', 'team_standing', 'Публикация командного зачёта', ARRAY['COMPETITION']::"RoleScope"[]),
  ('export.create', 'export', 'Выгрузки и печатные формы', ARRAY['COMPETITION']::"RoleScope"[]),
  ('notification.announce', 'notification', 'Объявления участникам', ARRAY['COMPETITION']::"RoleScope"[]),
  ('venue_node.manage', 'venue_node', 'Площадочный узел', ARRAY['COMPETITION']::"RoleScope"[]),
  ('write_lease.recover', 'write_lease', 'Аварийный возврат права записи', ARRAY['COMPETITION']::"RoleScope"[])
ON CONFLICT ("code") DO UPDATE SET "module" = EXCLUDED."module", "description" = EXCLUDED."description", "scopes" = EXCLUDED."scopes";

DELETE FROM "permission" WHERE "code" NOT IN ('platform.settings.manage', 'user.view', 'user.manage', 'role.manage', 'dictionary.manage', 'consent_template.manage', 'athlete.merge', 'audit.view', 'organization.approve', 'organization.create_child', 'organization.update', 'organization.members.view', 'organization.members.manage', 'athlete.view', 'athlete.create', 'athlete.update', 'athlete.archive', 'athlete.import', 'guardian.manage', 'consent.record', 'coach.manage', 'referee.manage', 'document.upload', 'document.view', 'document.verify', 'category.manage', 'ruleset.manage', 'venue.manage', 'competition.create', 'registration.create', 'ranking.manage', 'competition.view', 'competition.update', 'competition.delete', 'competition.publish', 'competition.transition', 'competition.members.manage', 'competition_category.manage', 'category.merge', 'registration.view', 'registration.approve', 'registration.reject', 'registration.return', 'registration.export', 'entry.withdraw', 'entry.transfer', 'admission.view', 'admission.override', 'checkin.view', 'checkin.perform', 'weighin.manage', 'weighin.record', 'weighin.view', 'medical.view', 'medical.record', 'draw.create', 'draw.publish', 'draw.republish', 'mat.manage', 'schedule.manage', 'schedule.publish', 'mat_assignment.manage', 'match.create', 'match.update', 'match.start', 'match.finish', 'match.cancel', 'scoring.create', 'scoring.update', 'result.confirm', 'result.amend', 'result.publish', 'team_standing.publish', 'export.create', 'notification.announce', 'venue_node.manage', 'write_lease.recover');

-- Системные роли (packages/contracts/src/roles.ts)
INSERT INTO "role" ("id", "code", "scope", "is_system", "name_key") VALUES
  ('01a0cfaa-3539-7239-bf28-b1620033709c'::uuid, 'SUPER_ADMIN', 'PLATFORM'::"RoleScope", true, 'roles.SUPER_ADMIN'),
  ('01a0cfaa-3539-72e3-9613-425b508f4948'::uuid, 'PLATFORM_ADMIN', 'PLATFORM'::"RoleScope", true, 'roles.PLATFORM_ADMIN'),
  ('01a0cfaa-353a-7407-99fa-700a7e26c364'::uuid, 'FEDERATION_ADMIN', 'ORGANIZATION'::"RoleScope", true, 'roles.FEDERATION_ADMIN'),
  ('01a0cfaa-353a-7ad4-b573-d2f3cb365217'::uuid, 'ORGANIZER', 'ORGANIZATION'::"RoleScope", true, 'roles.ORGANIZER'),
  ('01a0cfaa-353a-71d3-a36b-038a5264166c'::uuid, 'TOURNAMENT_MANAGER', 'COMPETITION'::"RoleScope", true, 'roles.TOURNAMENT_MANAGER'),
  ('01a0cfaa-353a-7198-a1dc-37346258928c'::uuid, 'SECRETARY', 'COMPETITION'::"RoleScope", true, 'roles.SECRETARY'),
  ('01a0cfaa-353a-7436-989d-b66bf7b90cc2'::uuid, 'CHIEF_REFEREE', 'COMPETITION'::"RoleScope", true, 'roles.CHIEF_REFEREE'),
  ('01a0cfaa-353a-74c1-a73c-b05ad2aa5fe3'::uuid, 'REFEREE', 'COMPETITION'::"RoleScope", true, 'roles.REFEREE'),
  ('01a0cfaa-353a-7b17-bc84-11e66782b7dd'::uuid, 'MEDICAL_STAFF', 'COMPETITION'::"RoleScope", true, 'roles.MEDICAL_STAFF'),
  ('01a0cfaa-353a-717f-8f14-cadf3d2eb907'::uuid, 'COACH', 'ORGANIZATION'::"RoleScope", true, 'roles.COACH'),
  ('01a0cfaa-353a-7fca-99ab-8a8299e149b1'::uuid, 'CLUB_MANAGER', 'ORGANIZATION'::"RoleScope", true, 'roles.CLUB_MANAGER')
ON CONFLICT ("code") DO UPDATE SET "scope" = EXCLUDED."scope", "is_system" = true, "name_key" = EXCLUDED."name_key";

-- Матрица «роль × permission» (PERMISSIONS.md, 4) — заменяется целиком для системных ролей
DELETE FROM "role_permission" rp USING "role" r WHERE rp."role_id" = r."id" AND r."is_system";

INSERT INTO "role_permission" ("role_id", "permission_code", "mode")
SELECT r."id", v.perm, v.mode::"GrantMode"
FROM (VALUES
  ('SUPER_ADMIN', 'platform.settings.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'user.view', 'DIRECT'),
  ('SUPER_ADMIN', 'user.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'role.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'dictionary.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'consent_template.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'athlete.merge', 'DIRECT'),
  ('SUPER_ADMIN', 'audit.view', 'DIRECT'),
  ('SUPER_ADMIN', 'organization.approve', 'DIRECT'),
  ('SUPER_ADMIN', 'organization.create_child', 'DIRECT'),
  ('SUPER_ADMIN', 'organization.update', 'DIRECT'),
  ('SUPER_ADMIN', 'organization.members.view', 'DIRECT'),
  ('SUPER_ADMIN', 'organization.members.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'athlete.view', 'DIRECT'),
  ('SUPER_ADMIN', 'athlete.create', 'DIRECT'),
  ('SUPER_ADMIN', 'athlete.update', 'DIRECT'),
  ('SUPER_ADMIN', 'athlete.archive', 'DIRECT'),
  ('SUPER_ADMIN', 'athlete.import', 'DIRECT'),
  ('SUPER_ADMIN', 'guardian.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'consent.record', 'DIRECT'),
  ('SUPER_ADMIN', 'coach.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'referee.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'document.upload', 'DIRECT'),
  ('SUPER_ADMIN', 'document.view', 'DIRECT'),
  ('SUPER_ADMIN', 'document.verify', 'DIRECT'),
  ('SUPER_ADMIN', 'category.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'ruleset.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'venue.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'competition.create', 'DIRECT'),
  ('SUPER_ADMIN', 'registration.create', 'DIRECT'),
  ('SUPER_ADMIN', 'ranking.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'competition.view', 'DIRECT'),
  ('SUPER_ADMIN', 'competition.update', 'DIRECT'),
  ('SUPER_ADMIN', 'competition.delete', 'DIRECT'),
  ('SUPER_ADMIN', 'competition.publish', 'DIRECT'),
  ('SUPER_ADMIN', 'competition.transition', 'DIRECT'),
  ('SUPER_ADMIN', 'competition.members.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'competition_category.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'category.merge', 'DIRECT'),
  ('SUPER_ADMIN', 'registration.view', 'DIRECT'),
  ('SUPER_ADMIN', 'registration.approve', 'DIRECT'),
  ('SUPER_ADMIN', 'registration.reject', 'DIRECT'),
  ('SUPER_ADMIN', 'registration.return', 'DIRECT'),
  ('SUPER_ADMIN', 'registration.export', 'DIRECT'),
  ('SUPER_ADMIN', 'entry.withdraw', 'DIRECT'),
  ('SUPER_ADMIN', 'entry.transfer', 'DIRECT'),
  ('SUPER_ADMIN', 'admission.view', 'DIRECT'),
  ('SUPER_ADMIN', 'admission.override', 'DIRECT'),
  ('SUPER_ADMIN', 'checkin.view', 'DIRECT'),
  ('SUPER_ADMIN', 'checkin.perform', 'DIRECT'),
  ('SUPER_ADMIN', 'weighin.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'weighin.record', 'DIRECT'),
  ('SUPER_ADMIN', 'weighin.view', 'DIRECT'),
  ('SUPER_ADMIN', 'medical.view', 'DIRECT'),
  ('SUPER_ADMIN', 'medical.record', 'DIRECT'),
  ('SUPER_ADMIN', 'draw.create', 'DIRECT'),
  ('SUPER_ADMIN', 'draw.publish', 'DIRECT'),
  ('SUPER_ADMIN', 'draw.republish', 'DIRECT'),
  ('SUPER_ADMIN', 'mat.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'schedule.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'schedule.publish', 'DIRECT'),
  ('SUPER_ADMIN', 'mat_assignment.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'match.create', 'DIRECT'),
  ('SUPER_ADMIN', 'match.update', 'DIRECT'),
  ('SUPER_ADMIN', 'match.start', 'DIRECT'),
  ('SUPER_ADMIN', 'match.finish', 'DIRECT'),
  ('SUPER_ADMIN', 'match.cancel', 'DIRECT'),
  ('SUPER_ADMIN', 'scoring.create', 'DIRECT'),
  ('SUPER_ADMIN', 'scoring.update', 'DIRECT'),
  ('SUPER_ADMIN', 'result.confirm', 'DIRECT'),
  ('SUPER_ADMIN', 'result.amend', 'DIRECT'),
  ('SUPER_ADMIN', 'result.publish', 'DIRECT'),
  ('SUPER_ADMIN', 'team_standing.publish', 'DIRECT'),
  ('SUPER_ADMIN', 'export.create', 'DIRECT'),
  ('SUPER_ADMIN', 'notification.announce', 'DIRECT'),
  ('SUPER_ADMIN', 'venue_node.manage', 'DIRECT'),
  ('SUPER_ADMIN', 'write_lease.recover', 'DIRECT'),
  ('PLATFORM_ADMIN', 'user.view', 'DIRECT'),
  ('PLATFORM_ADMIN', 'user.manage', 'DIRECT'),
  ('PLATFORM_ADMIN', 'dictionary.manage', 'DIRECT'),
  ('PLATFORM_ADMIN', 'consent_template.manage', 'DIRECT'),
  ('PLATFORM_ADMIN', 'athlete.merge', 'DIRECT'),
  ('PLATFORM_ADMIN', 'audit.view', 'DIRECT'),
  ('PLATFORM_ADMIN', 'organization.approve', 'DIRECT'),
  ('PLATFORM_ADMIN', 'organization.update', 'DIRECT'),
  ('PLATFORM_ADMIN', 'organization.members.view', 'DIRECT'),
  ('PLATFORM_ADMIN', 'organization.members.manage', 'DIRECT'),
  ('PLATFORM_ADMIN', 'athlete.view', 'DIRECT'),
  ('PLATFORM_ADMIN', 'category.manage', 'DIRECT'),
  ('PLATFORM_ADMIN', 'ruleset.manage', 'DIRECT'),
  ('PLATFORM_ADMIN', 'competition.view', 'DIRECT'),
  ('FEDERATION_ADMIN', 'organization.approve', 'DIRECT'),
  ('FEDERATION_ADMIN', 'organization.create_child', 'DIRECT'),
  ('FEDERATION_ADMIN', 'organization.update', 'DIRECT'),
  ('FEDERATION_ADMIN', 'organization.members.view', 'DIRECT'),
  ('FEDERATION_ADMIN', 'organization.members.manage', 'DIRECT'),
  ('FEDERATION_ADMIN', 'athlete.view', 'DIRECT'),
  ('FEDERATION_ADMIN', 'referee.manage', 'DIRECT'),
  ('FEDERATION_ADMIN', 'category.manage', 'DIRECT'),
  ('FEDERATION_ADMIN', 'ruleset.manage', 'DIRECT'),
  ('FEDERATION_ADMIN', 'venue.manage', 'DIRECT'),
  ('FEDERATION_ADMIN', 'competition.create', 'DIRECT'),
  ('FEDERATION_ADMIN', 'ranking.manage', 'DIRECT'),
  ('FEDERATION_ADMIN', 'competition.view', 'DIRECT'),
  ('ORGANIZER', 'audit.view', 'INHERITED'),
  ('ORGANIZER', 'organization.update', 'DIRECT'),
  ('ORGANIZER', 'organization.members.view', 'DIRECT'),
  ('ORGANIZER', 'document.view', 'INHERITED'),
  ('ORGANIZER', 'document.verify', 'INHERITED'),
  ('ORGANIZER', 'category.manage', 'DIRECT'),
  ('ORGANIZER', 'ruleset.manage', 'DIRECT'),
  ('ORGANIZER', 'venue.manage', 'DIRECT'),
  ('ORGANIZER', 'competition.create', 'DIRECT'),
  ('ORGANIZER', 'competition.view', 'INHERITED'),
  ('ORGANIZER', 'competition.update', 'INHERITED'),
  ('ORGANIZER', 'competition.delete', 'INHERITED'),
  ('ORGANIZER', 'competition.publish', 'INHERITED'),
  ('ORGANIZER', 'competition.transition', 'INHERITED'),
  ('ORGANIZER', 'competition.members.manage', 'INHERITED'),
  ('ORGANIZER', 'competition_category.manage', 'INHERITED'),
  ('ORGANIZER', 'category.merge', 'INHERITED'),
  ('ORGANIZER', 'registration.view', 'INHERITED'),
  ('ORGANIZER', 'registration.approve', 'INHERITED'),
  ('ORGANIZER', 'registration.reject', 'INHERITED'),
  ('ORGANIZER', 'registration.return', 'INHERITED'),
  ('ORGANIZER', 'registration.export', 'INHERITED'),
  ('ORGANIZER', 'entry.withdraw', 'INHERITED'),
  ('ORGANIZER', 'entry.transfer', 'INHERITED'),
  ('ORGANIZER', 'admission.view', 'INHERITED'),
  ('ORGANIZER', 'admission.override', 'INHERITED'),
  ('ORGANIZER', 'checkin.view', 'INHERITED'),
  ('ORGANIZER', 'checkin.perform', 'INHERITED'),
  ('ORGANIZER', 'weighin.manage', 'INHERITED'),
  ('ORGANIZER', 'weighin.record', 'INHERITED'),
  ('ORGANIZER', 'weighin.view', 'INHERITED'),
  ('ORGANIZER', 'draw.create', 'INHERITED'),
  ('ORGANIZER', 'draw.publish', 'INHERITED'),
  ('ORGANIZER', 'mat.manage', 'INHERITED'),
  ('ORGANIZER', 'schedule.manage', 'INHERITED'),
  ('ORGANIZER', 'schedule.publish', 'INHERITED'),
  ('ORGANIZER', 'mat_assignment.manage', 'INHERITED'),
  ('ORGANIZER', 'match.create', 'INHERITED'),
  ('ORGANIZER', 'match.update', 'INHERITED'),
  ('ORGANIZER', 'match.cancel', 'INHERITED'),
  ('ORGANIZER', 'result.publish', 'INHERITED'),
  ('ORGANIZER', 'team_standing.publish', 'INHERITED'),
  ('ORGANIZER', 'export.create', 'INHERITED'),
  ('ORGANIZER', 'notification.announce', 'INHERITED'),
  ('ORGANIZER', 'venue_node.manage', 'INHERITED'),
  ('ORGANIZER', 'write_lease.recover', 'INHERITED'),
  ('TOURNAMENT_MANAGER', 'audit.view', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'document.view', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'document.verify', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'competition.view', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'competition.update', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'competition.delete', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'competition.publish', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'competition.transition', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'competition.members.manage', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'competition_category.manage', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'category.merge', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'registration.view', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'registration.approve', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'registration.reject', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'registration.return', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'registration.export', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'entry.withdraw', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'entry.transfer', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'admission.view', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'admission.override', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'checkin.view', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'checkin.perform', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'weighin.manage', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'weighin.record', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'weighin.view', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'draw.create', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'draw.publish', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'mat.manage', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'schedule.manage', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'schedule.publish', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'mat_assignment.manage', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'match.create', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'match.update', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'match.cancel', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'result.publish', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'team_standing.publish', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'export.create', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'notification.announce', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'venue_node.manage', 'DIRECT'),
  ('TOURNAMENT_MANAGER', 'write_lease.recover', 'DIRECT'),
  ('SECRETARY', 'document.view', 'DIRECT'),
  ('SECRETARY', 'document.verify', 'DIRECT'),
  ('SECRETARY', 'competition.view', 'DIRECT'),
  ('SECRETARY', 'registration.view', 'DIRECT'),
  ('SECRETARY', 'registration.approve', 'DIRECT'),
  ('SECRETARY', 'registration.reject', 'DIRECT'),
  ('SECRETARY', 'registration.return', 'DIRECT'),
  ('SECRETARY', 'registration.export', 'DIRECT'),
  ('SECRETARY', 'entry.transfer', 'DIRECT'),
  ('SECRETARY', 'admission.view', 'DIRECT'),
  ('SECRETARY', 'checkin.view', 'DIRECT'),
  ('SECRETARY', 'checkin.perform', 'DIRECT'),
  ('SECRETARY', 'weighin.record', 'DIRECT'),
  ('SECRETARY', 'weighin.view', 'DIRECT'),
  ('SECRETARY', 'draw.create', 'DIRECT'),
  ('SECRETARY', 'schedule.manage', 'DIRECT'),
  ('SECRETARY', 'match.create', 'DIRECT'),
  ('SECRETARY', 'match.update', 'DIRECT'),
  ('SECRETARY', 'export.create', 'DIRECT'),
  ('CHIEF_REFEREE', 'audit.view', 'DIRECT'),
  ('CHIEF_REFEREE', 'competition.view', 'DIRECT'),
  ('CHIEF_REFEREE', 'admission.view', 'DIRECT'),
  ('CHIEF_REFEREE', 'weighin.view', 'DIRECT'),
  ('CHIEF_REFEREE', 'draw.create', 'DIRECT'),
  ('CHIEF_REFEREE', 'draw.publish', 'DIRECT'),
  ('CHIEF_REFEREE', 'draw.republish', 'DIRECT'),
  ('CHIEF_REFEREE', 'mat_assignment.manage', 'DIRECT'),
  ('CHIEF_REFEREE', 'match.update', 'DIRECT'),
  ('CHIEF_REFEREE', 'match.start', 'DIRECT'),
  ('CHIEF_REFEREE', 'match.finish', 'DIRECT'),
  ('CHIEF_REFEREE', 'match.cancel', 'DIRECT'),
  ('CHIEF_REFEREE', 'scoring.create', 'DIRECT'),
  ('CHIEF_REFEREE', 'scoring.update', 'DIRECT'),
  ('CHIEF_REFEREE', 'result.confirm', 'DIRECT'),
  ('CHIEF_REFEREE', 'result.amend', 'DIRECT'),
  ('CHIEF_REFEREE', 'result.publish', 'DIRECT'),
  ('CHIEF_REFEREE', 'export.create', 'DIRECT'),
  ('REFEREE', 'competition.view', 'LIMITED'),
  ('REFEREE', 'match.update', 'POLICY'),
  ('REFEREE', 'match.start', 'POLICY'),
  ('REFEREE', 'match.finish', 'POLICY'),
  ('REFEREE', 'scoring.create', 'POLICY'),
  ('REFEREE', 'scoring.update', 'POLICY'),
  ('REFEREE', 'result.confirm', 'POLICY'),
  ('MEDICAL_STAFF', 'competition.view', 'LIMITED'),
  ('MEDICAL_STAFF', 'admission.view', 'DIRECT'),
  ('MEDICAL_STAFF', 'medical.view', 'DIRECT'),
  ('MEDICAL_STAFF', 'medical.record', 'DIRECT'),
  ('COACH', 'athlete.view', 'DIRECT'),
  ('COACH', 'athlete.create', 'DIRECT'),
  ('COACH', 'athlete.update', 'POLICY'),
  ('COACH', 'guardian.manage', 'POLICY'),
  ('COACH', 'consent.record', 'POLICY'),
  ('COACH', 'document.upload', 'DIRECT'),
  ('COACH', 'document.view', 'POLICY'),
  ('COACH', 'registration.create', 'DIRECT'),
  ('CLUB_MANAGER', 'organization.update', 'DIRECT'),
  ('CLUB_MANAGER', 'organization.members.view', 'DIRECT'),
  ('CLUB_MANAGER', 'organization.members.manage', 'DIRECT'),
  ('CLUB_MANAGER', 'athlete.view', 'DIRECT'),
  ('CLUB_MANAGER', 'athlete.create', 'DIRECT'),
  ('CLUB_MANAGER', 'athlete.update', 'DIRECT'),
  ('CLUB_MANAGER', 'athlete.archive', 'DIRECT'),
  ('CLUB_MANAGER', 'athlete.import', 'DIRECT'),
  ('CLUB_MANAGER', 'guardian.manage', 'DIRECT'),
  ('CLUB_MANAGER', 'consent.record', 'DIRECT'),
  ('CLUB_MANAGER', 'coach.manage', 'DIRECT'),
  ('CLUB_MANAGER', 'document.upload', 'DIRECT'),
  ('CLUB_MANAGER', 'document.view', 'DIRECT'),
  ('CLUB_MANAGER', 'registration.create', 'DIRECT')
) AS v(role, perm, mode)
JOIN "role" r ON r."code" = v.role;

-- Права ролей изменились → кэш эффективных прав всех пользователей устарел
UPDATE "user" SET "permissions_version" = "permissions_version" + 1;

-- Справочники (packages/db/scripts/reference-data.ts). Существующие записи не перезаписываются.
INSERT INTO "country" ("code", "name_ru", "name_en") VALUES
  ('RU', 'Россия', 'Russia'),
  ('BY', 'Беларусь', 'Belarus'),
  ('KZ', 'Казахстан', 'Kazakhstan'),
  ('UZ', 'Узбекистан', 'Uzbekistan'),
  ('KG', 'Киргизия', 'Kyrgyzstan'),
  ('TJ', 'Таджикистан', 'Tajikistan'),
  ('TM', 'Туркменистан', 'Turkmenistan'),
  ('AM', 'Армения', 'Armenia'),
  ('AZ', 'Азербайджан', 'Azerbaijan'),
  ('GE', 'Грузия', 'Georgia'),
  ('MD', 'Молдова', 'Moldova'),
  ('MN', 'Монголия', 'Mongolia'),
  ('RS', 'Сербия', 'Serbia'),
  ('BG', 'Болгария', 'Bulgaria'),
  ('CN', 'Китай', 'China'),
  ('IN', 'Индия', 'India')
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "region" ("id", "country_code", "code", "name_ru", "name_en") VALUES
  ('01a0cfaa-353a-77d9-b257-86b5dca73ec3'::uuid, 'RU', 'RU-AD', 'Республика Адыгея', 'Republic of Adygea'),
  ('01a0cfaa-353a-7d1d-b475-50a3fa9e143b'::uuid, 'RU', 'RU-AL', 'Республика Алтай', 'Altai Republic'),
  ('01a0cfaa-353a-7856-9d7c-1dfce2557604'::uuid, 'RU', 'RU-BA', 'Республика Башкортостан', 'Republic of Bashkortostan'),
  ('01a0cfaa-353a-7088-8092-1c2752f0bfd1'::uuid, 'RU', 'RU-BU', 'Республика Бурятия', 'Republic of Buryatia'),
  ('01a0cfaa-353a-7bda-8c92-fe86ff181bb9'::uuid, 'RU', 'RU-CE', 'Чеченская Республика', 'Chechen Republic'),
  ('01a0cfaa-353a-7041-a251-84047899244f'::uuid, 'RU', 'RU-CU', 'Чувашская Республика', 'Chuvash Republic'),
  ('01a0cfaa-353a-752b-b421-97e89c584c10'::uuid, 'RU', 'RU-DA', 'Республика Дагестан', 'Republic of Dagestan'),
  ('01a0cfaa-353a-7be5-a613-a4b925046985'::uuid, 'RU', 'RU-IN', 'Республика Ингушетия', 'Republic of Ingushetia'),
  ('01a0cfaa-353a-76c9-bd4c-0aeedccc4d29'::uuid, 'RU', 'RU-KB', 'Кабардино-Балкарская Республика', 'Kabardino-Balkarian Republic'),
  ('01a0cfaa-353a-7edd-8d22-66675db9778c'::uuid, 'RU', 'RU-KL', 'Республика Калмыкия', 'Republic of Kalmykia'),
  ('01a0cfaa-353a-7036-94e2-19e6de581e47'::uuid, 'RU', 'RU-KC', 'Карачаево-Черкесская Республика', 'Karachay-Cherkess Republic'),
  ('01a0cfaa-353a-7eff-8363-444a6a5fc43a'::uuid, 'RU', 'RU-KR', 'Республика Карелия', 'Republic of Karelia'),
  ('01a0cfaa-353a-7936-af6f-ff714d6252a8'::uuid, 'RU', 'RU-KO', 'Республика Коми', 'Komi Republic'),
  ('01a0cfaa-353a-7fdb-a9f9-a2c1c75397a8'::uuid, 'RU', 'RU-ME', 'Республика Марий Эл', 'Mari El Republic'),
  ('01a0cfaa-353a-75b8-97c3-621984631fee'::uuid, 'RU', 'RU-MO', 'Республика Мордовия', 'Republic of Mordovia'),
  ('01a0cfaa-353a-78b6-a53c-5b8125f342ff'::uuid, 'RU', 'RU-SA', 'Республика Саха (Якутия)', 'Sakha (Yakutia) Republic'),
  ('01a0cfaa-353a-776c-9c96-051d3cf059d0'::uuid, 'RU', 'RU-SE', 'Республика Северная Осетия — Алания', 'Republic of North Ossetia–Alania'),
  ('01a0cfaa-353a-7fe8-ac29-e7763a90da28'::uuid, 'RU', 'RU-TA', 'Республика Татарстан', 'Republic of Tatarstan'),
  ('01a0cfaa-353a-7453-8dc5-1278683ec465'::uuid, 'RU', 'RU-TY', 'Республика Тыва', 'Tuva Republic'),
  ('01a0cfaa-353a-7f4f-bca7-a375f2f62a31'::uuid, 'RU', 'RU-UD', 'Удмуртская Республика', 'Udmurt Republic'),
  ('01a0cfaa-353a-7706-9d91-7dec6d1a4d15'::uuid, 'RU', 'RU-KK', 'Республика Хакасия', 'Republic of Khakassia'),
  ('01a0cfaa-353a-704c-8cdc-023b9cd0d397'::uuid, 'RU', 'RU-ALT', 'Алтайский край', 'Altai Krai'),
  ('01a0cfaa-353a-7755-a459-61cd33a9a19f'::uuid, 'RU', 'RU-ZAB', 'Забайкальский край', 'Zabaykalsky Krai'),
  ('01a0cfaa-353a-7d47-8b38-cbcc26bdda0d'::uuid, 'RU', 'RU-KAM', 'Камчатский край', 'Kamchatka Krai'),
  ('01a0cfaa-353a-72f5-9747-791b9f9bf0cc'::uuid, 'RU', 'RU-KDA', 'Краснодарский край', 'Krasnodar Krai'),
  ('01a0cfaa-353a-7bbe-8564-52844422be43'::uuid, 'RU', 'RU-KYA', 'Красноярский край', 'Krasnoyarsk Krai'),
  ('01a0cfaa-353a-7a48-86b1-3ca3e9ab80bf'::uuid, 'RU', 'RU-PER', 'Пермский край', 'Perm Krai'),
  ('01a0cfaa-353a-7311-a71d-2ff9d52ec6bd'::uuid, 'RU', 'RU-PRI', 'Приморский край', 'Primorsky Krai'),
  ('01a0cfaa-353a-789d-933a-190888d28bb5'::uuid, 'RU', 'RU-STA', 'Ставропольский край', 'Stavropol Krai'),
  ('01a0cfaa-353b-7d58-b6c0-6055dcddc046'::uuid, 'RU', 'RU-KHA', 'Хабаровский край', 'Khabarovsk Krai'),
  ('01a0cfaa-353b-753a-a162-9cc831b8ea7c'::uuid, 'RU', 'RU-AMU', 'Амурская область', 'Amur Oblast'),
  ('01a0cfaa-353b-7ad5-a2f2-c4c2459c149c'::uuid, 'RU', 'RU-ARK', 'Архангельская область', 'Arkhangelsk Oblast'),
  ('01a0cfaa-353b-78f4-9805-8e905831432c'::uuid, 'RU', 'RU-AST', 'Астраханская область', 'Astrakhan Oblast'),
  ('01a0cfaa-353b-7e85-a776-964fc0cbbfed'::uuid, 'RU', 'RU-BEL', 'Белгородская область', 'Belgorod Oblast'),
  ('01a0cfaa-353b-74f0-8a65-8af81b65933e'::uuid, 'RU', 'RU-BRY', 'Брянская область', 'Bryansk Oblast'),
  ('01a0cfaa-353b-71ec-9187-eb45401805b7'::uuid, 'RU', 'RU-VLA', 'Владимирская область', 'Vladimir Oblast'),
  ('01a0cfaa-353b-7b05-99b8-34f0cdf2e1ad'::uuid, 'RU', 'RU-VGG', 'Волгоградская область', 'Volgograd Oblast'),
  ('01a0cfaa-353b-75ea-90f6-c5bdbd02d81b'::uuid, 'RU', 'RU-VLG', 'Вологодская область', 'Vologda Oblast'),
  ('01a0cfaa-353b-7d83-80ff-a119e065bf75'::uuid, 'RU', 'RU-VOR', 'Воронежская область', 'Voronezh Oblast'),
  ('01a0cfaa-353b-7612-94ec-a7026ebcd106'::uuid, 'RU', 'RU-IVA', 'Ивановская область', 'Ivanovo Oblast'),
  ('01a0cfaa-353b-73ae-8a57-a4ea1d397ac8'::uuid, 'RU', 'RU-IRK', 'Иркутская область', 'Irkutsk Oblast'),
  ('01a0cfaa-353b-7873-bd66-d617574afb34'::uuid, 'RU', 'RU-KGD', 'Калининградская область', 'Kaliningrad Oblast'),
  ('01a0cfaa-353b-7a46-a2a5-1c953da72d30'::uuid, 'RU', 'RU-KLU', 'Калужская область', 'Kaluga Oblast'),
  ('01a0cfaa-353b-7bb6-86c9-0577c6614d6a'::uuid, 'RU', 'RU-KEM', 'Кемеровская область — Кузбасс', 'Kemerovo Oblast — Kuzbass'),
  ('01a0cfaa-353b-757d-8ca9-f33b41d5f1a0'::uuid, 'RU', 'RU-KIR', 'Кировская область', 'Kirov Oblast'),
  ('01a0cfaa-353b-7e38-83f0-e31967a3b21b'::uuid, 'RU', 'RU-KOS', 'Костромская область', 'Kostroma Oblast'),
  ('01a0cfaa-353b-7cc5-a113-f237eca05212'::uuid, 'RU', 'RU-KGN', 'Курганская область', 'Kurgan Oblast'),
  ('01a0cfaa-353b-74ca-8e2f-3d32bb720d1c'::uuid, 'RU', 'RU-KRS', 'Курская область', 'Kursk Oblast'),
  ('01a0cfaa-353b-704b-bef3-bda4c3032163'::uuid, 'RU', 'RU-LEN', 'Ленинградская область', 'Leningrad Oblast'),
  ('01a0cfaa-353b-7534-b49f-16fa4444b302'::uuid, 'RU', 'RU-LIP', 'Липецкая область', 'Lipetsk Oblast'),
  ('01a0cfaa-353b-7ff0-a9b8-70bd55ffa9d7'::uuid, 'RU', 'RU-MAG', 'Магаданская область', 'Magadan Oblast'),
  ('01a0cfaa-353b-78fb-b0c2-f24f43a6d735'::uuid, 'RU', 'RU-MOS', 'Московская область', 'Moscow Oblast'),
  ('01a0cfaa-353b-7335-973c-139232e7368f'::uuid, 'RU', 'RU-MUR', 'Мурманская область', 'Murmansk Oblast'),
  ('01a0cfaa-353b-794c-9c7a-0a0b30b00d1d'::uuid, 'RU', 'RU-NIZ', 'Нижегородская область', 'Nizhny Novgorod Oblast'),
  ('01a0cfaa-353b-764b-95e3-ea1c5a30376c'::uuid, 'RU', 'RU-NGR', 'Новгородская область', 'Novgorod Oblast'),
  ('01a0cfaa-353b-74c9-a313-78ce1740b08c'::uuid, 'RU', 'RU-NVS', 'Новосибирская область', 'Novosibirsk Oblast'),
  ('01a0cfaa-353b-76fa-8ad4-f64b7eb58137'::uuid, 'RU', 'RU-OMS', 'Омская область', 'Omsk Oblast'),
  ('01a0cfaa-353b-71ba-b3d1-a68f9179e047'::uuid, 'RU', 'RU-ORE', 'Оренбургская область', 'Orenburg Oblast'),
  ('01a0cfaa-353b-7977-a273-1fdba9072dcc'::uuid, 'RU', 'RU-ORL', 'Орловская область', 'Oryol Oblast'),
  ('01a0cfaa-353b-7898-899a-b2dfb50730a5'::uuid, 'RU', 'RU-PNZ', 'Пензенская область', 'Penza Oblast'),
  ('01a0cfaa-353b-76f6-b020-47c2c86a7514'::uuid, 'RU', 'RU-PSK', 'Псковская область', 'Pskov Oblast'),
  ('01a0cfaa-353b-7e1b-a2ef-7ad459cc2bb4'::uuid, 'RU', 'RU-ROS', 'Ростовская область', 'Rostov Oblast'),
  ('01a0cfaa-353b-7db5-9033-b5cf70cc08e7'::uuid, 'RU', 'RU-RYA', 'Рязанская область', 'Ryazan Oblast'),
  ('01a0cfaa-353b-7977-84ba-daff511cdf57'::uuid, 'RU', 'RU-SAM', 'Самарская область', 'Samara Oblast'),
  ('01a0cfaa-353b-76cf-b083-45d91e95b309'::uuid, 'RU', 'RU-SAR', 'Саратовская область', 'Saratov Oblast'),
  ('01a0cfaa-353b-7963-8db4-43db23280d0e'::uuid, 'RU', 'RU-SAK', 'Сахалинская область', 'Sakhalin Oblast'),
  ('01a0cfaa-353b-7413-aafa-f88ed98d778e'::uuid, 'RU', 'RU-SVE', 'Свердловская область', 'Sverdlovsk Oblast'),
  ('01a0cfaa-353b-7a55-8c98-6ee93738d1af'::uuid, 'RU', 'RU-SMO', 'Смоленская область', 'Smolensk Oblast'),
  ('01a0cfaa-353b-7d78-a2d6-c2984e145025'::uuid, 'RU', 'RU-TAM', 'Тамбовская область', 'Tambov Oblast'),
  ('01a0cfaa-353b-749b-88b6-542f1f22955c'::uuid, 'RU', 'RU-TVE', 'Тверская область', 'Tver Oblast'),
  ('01a0cfaa-353b-79e2-9235-b0b8687fe2ed'::uuid, 'RU', 'RU-TOM', 'Томская область', 'Tomsk Oblast'),
  ('01a0cfaa-353b-7920-af92-3ab6310a105f'::uuid, 'RU', 'RU-TUL', 'Тульская область', 'Tula Oblast'),
  ('01a0cfaa-353b-758d-91c1-e64e414833fe'::uuid, 'RU', 'RU-TYU', 'Тюменская область', 'Tyumen Oblast'),
  ('01a0cfaa-353b-7a82-8100-5c0d1eead0ce'::uuid, 'RU', 'RU-ULY', 'Ульяновская область', 'Ulyanovsk Oblast'),
  ('01a0cfaa-353b-77eb-953c-e58dbf98049e'::uuid, 'RU', 'RU-CHE', 'Челябинская область', 'Chelyabinsk Oblast'),
  ('01a0cfaa-353b-7856-8a15-8748044e87d7'::uuid, 'RU', 'RU-YAR', 'Ярославская область', 'Yaroslavl Oblast'),
  ('01a0cfaa-353b-7727-8ba3-a38c722ed543'::uuid, 'RU', 'RU-MOW', 'Москва', 'Moscow'),
  ('01a0cfaa-353b-79f9-bec1-a4600582f84d'::uuid, 'RU', 'RU-SPE', 'Санкт-Петербург', 'Saint Petersburg'),
  ('01a0cfaa-353b-75d0-8d3a-0e32ca2c3e8b'::uuid, 'RU', 'RU-YEV', 'Еврейская автономная область', 'Jewish Autonomous Oblast'),
  ('01a0cfaa-353b-77f4-99f6-c53eff44deee'::uuid, 'RU', 'RU-NEN', 'Ненецкий автономный округ', 'Nenets Autonomous Okrug'),
  ('01a0cfaa-353b-7bdb-abac-ad54e16b6cd2'::uuid, 'RU', 'RU-KHM', 'Ханты-Мансийский автономный округ — Югра', 'Khanty-Mansi Autonomous Okrug — Yugra'),
  ('01a0cfaa-353b-7d64-acb5-4748e7b21961'::uuid, 'RU', 'RU-CHU', 'Чукотский автономный округ', 'Chukotka Autonomous Okrug'),
  ('01a0cfaa-353b-7e93-8ea3-f8077a8d99f0'::uuid, 'RU', 'RU-YAN', 'Ямало-Ненецкий автономный округ', 'Yamalo-Nenets Autonomous Okrug')
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "sport_rank" ("code", "name_ru", "name_en", "rank_order") VALUES
  ('YOUTH_3', '3 юношеский разряд', '3rd youth rank', 1),
  ('YOUTH_2', '2 юношеский разряд', '2nd youth rank', 2),
  ('YOUTH_1', '1 юношеский разряд', '1st youth rank', 3),
  ('SPORT_3', '3 спортивный разряд', '3rd sports rank', 4),
  ('SPORT_2', '2 спортивный разряд', '2nd sports rank', 5),
  ('SPORT_1', '1 спортивный разряд', '1st sports rank', 6),
  ('CMS', 'Кандидат в мастера спорта', 'Candidate Master of Sport', 7),
  ('MS', 'Мастер спорта России', 'Master of Sport of Russia', 8),
  ('MSIC', 'Мастер спорта России международного класса', 'Master of Sport, International Class', 9),
  ('HMS', 'Заслуженный мастер спорта России', 'Honoured Master of Sport of Russia', 10)
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "referee_category" ("code", "name_ru", "name_en", "rank_order") VALUES
  ('YOUNG', 'Юный спортивный судья', 'Young sports referee', 1),
  ('CAT_3', 'Спортивный судья третьей категории', 'Sports referee, 3rd category', 2),
  ('CAT_2', 'Спортивный судья второй категории', 'Sports referee, 2nd category', 3),
  ('CAT_1', 'Спортивный судья первой категории', 'Sports referee, 1st category', 4),
  ('NATIONAL', 'Спортивный судья всероссийской категории', 'Sports referee, national category', 5),
  ('INTERNATIONAL', 'Судья международной категории', 'International referee', 6)
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "discipline" ("code", "name_ru", "name_en") VALUES
  ('SPORT_SAMBO', 'Самбо', 'Sport sambo'),
  ('COMBAT_SAMBO', 'Боевое самбо', 'Combat sambo'),
  ('BEACH_SAMBO', 'Пляжное самбо', 'Beach sambo'),
  ('DEMO_SAMBO', 'Демонстрационное самбо', 'Demonstration sambo')
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "document_type" ("code", "name_ru", "name_en", "sensitivity", "allowed_mime", "max_size_bytes", "retention_days") VALUES
  ('MEDICAL_CERTIFICATE', 'Медицинская справка о допуске', 'Medical clearance certificate', 'HEALTH'::"Sensitivity", 'application/pdf,image/jpeg,image/png', 10485760, 400),
  ('INSURANCE_POLICY', 'Полис страхования от несчастных случаев', 'Accident insurance policy', 'GENERAL'::"Sensitivity", 'application/pdf,image/jpeg,image/png', 10485760, 400),
  ('BIRTH_CERTIFICATE', 'Свидетельство о рождении', 'Birth certificate', 'IDENTITY'::"Sensitivity", 'application/pdf,image/jpeg,image/png', 10485760, 365),
  ('PASSPORT', 'Паспорт', 'Passport', 'IDENTITY'::"Sensitivity", 'application/pdf,image/jpeg,image/png', 10485760, 365),
  ('SPORT_RANK_ORDER', 'Приказ о присвоении разряда', 'Sports rank assignment order', 'GENERAL'::"Sensitivity", 'application/pdf,image/jpeg,image/png', 10485760, 730),
  ('CONSENT_SCAN', 'Скан согласия законного представителя', 'Guardian consent scan', 'GENERAL'::"Sensitivity", 'application/pdf,image/jpeg,image/png', 10485760, 1825),
  ('OTHER', 'Иной документ', 'Other document', 'GENERAL'::"Sensitivity", 'application/pdf,image/jpeg,image/png', 10485760, 365)
ON CONFLICT ("code") DO NOTHING;
