// Справочники, которые создаются миграцией данных (DATABASE.md, 10). Дальше меняются через `dictionary.manage`.

export const COUNTRIES: [code: string, ru: string, en: string][] = [
  ['RU', 'Россия', 'Russia'],
  ['BY', 'Беларусь', 'Belarus'],
  ['KZ', 'Казахстан', 'Kazakhstan'],
  ['UZ', 'Узбекистан', 'Uzbekistan'],
  ['KG', 'Киргизия', 'Kyrgyzstan'],
  ['TJ', 'Таджикистан', 'Tajikistan'],
  ['TM', 'Туркменистан', 'Turkmenistan'],
  ['AM', 'Армения', 'Armenia'],
  ['AZ', 'Азербайджан', 'Azerbaijan'],
  ['GE', 'Грузия', 'Georgia'],
  ['MD', 'Молдова', 'Moldova'],
  ['MN', 'Монголия', 'Mongolia'],
  ['RS', 'Сербия', 'Serbia'],
  ['BG', 'Болгария', 'Bulgaria'],
  ['CN', 'Китай', 'China'],
  ['IN', 'Индия', 'India'],
];

// Субъекты РФ по ISO 3166-2:RU. Другие записи добавляются через справочник (`dictionary.manage`).
export const RU_REGIONS: [code: string, ru: string, en: string][] = [
  ['RU-AD', 'Республика Адыгея', 'Republic of Adygea'],
  ['RU-AL', 'Республика Алтай', 'Altai Republic'],
  ['RU-BA', 'Республика Башкортостан', 'Republic of Bashkortostan'],
  ['RU-BU', 'Республика Бурятия', 'Republic of Buryatia'],
  ['RU-CE', 'Чеченская Республика', 'Chechen Republic'],
  ['RU-CU', 'Чувашская Республика', 'Chuvash Republic'],
  ['RU-DA', 'Республика Дагестан', 'Republic of Dagestan'],
  ['RU-IN', 'Республика Ингушетия', 'Republic of Ingushetia'],
  ['RU-KB', 'Кабардино-Балкарская Республика', 'Kabardino-Balkarian Republic'],
  ['RU-KL', 'Республика Калмыкия', 'Republic of Kalmykia'],
  ['RU-KC', 'Карачаево-Черкесская Республика', 'Karachay-Cherkess Republic'],
  ['RU-KR', 'Республика Карелия', 'Republic of Karelia'],
  ['RU-KO', 'Республика Коми', 'Komi Republic'],
  ['RU-ME', 'Республика Марий Эл', 'Mari El Republic'],
  ['RU-MO', 'Республика Мордовия', 'Republic of Mordovia'],
  ['RU-SA', 'Республика Саха (Якутия)', 'Sakha (Yakutia) Republic'],
  ['RU-SE', 'Республика Северная Осетия — Алания', 'Republic of North Ossetia–Alania'],
  ['RU-TA', 'Республика Татарстан', 'Republic of Tatarstan'],
  ['RU-TY', 'Республика Тыва', 'Tuva Republic'],
  ['RU-UD', 'Удмуртская Республика', 'Udmurt Republic'],
  ['RU-KK', 'Республика Хакасия', 'Republic of Khakassia'],
  ['RU-ALT', 'Алтайский край', 'Altai Krai'],
  ['RU-ZAB', 'Забайкальский край', 'Zabaykalsky Krai'],
  ['RU-KAM', 'Камчатский край', 'Kamchatka Krai'],
  ['RU-KDA', 'Краснодарский край', 'Krasnodar Krai'],
  ['RU-KYA', 'Красноярский край', 'Krasnoyarsk Krai'],
  ['RU-PER', 'Пермский край', 'Perm Krai'],
  ['RU-PRI', 'Приморский край', 'Primorsky Krai'],
  ['RU-STA', 'Ставропольский край', 'Stavropol Krai'],
  ['RU-KHA', 'Хабаровский край', 'Khabarovsk Krai'],
  ['RU-AMU', 'Амурская область', 'Amur Oblast'],
  ['RU-ARK', 'Архангельская область', 'Arkhangelsk Oblast'],
  ['RU-AST', 'Астраханская область', 'Astrakhan Oblast'],
  ['RU-BEL', 'Белгородская область', 'Belgorod Oblast'],
  ['RU-BRY', 'Брянская область', 'Bryansk Oblast'],
  ['RU-VLA', 'Владимирская область', 'Vladimir Oblast'],
  ['RU-VGG', 'Волгоградская область', 'Volgograd Oblast'],
  ['RU-VLG', 'Вологодская область', 'Vologda Oblast'],
  ['RU-VOR', 'Воронежская область', 'Voronezh Oblast'],
  ['RU-IVA', 'Ивановская область', 'Ivanovo Oblast'],
  ['RU-IRK', 'Иркутская область', 'Irkutsk Oblast'],
  ['RU-KGD', 'Калининградская область', 'Kaliningrad Oblast'],
  ['RU-KLU', 'Калужская область', 'Kaluga Oblast'],
  ['RU-KEM', 'Кемеровская область — Кузбасс', 'Kemerovo Oblast — Kuzbass'],
  ['RU-KIR', 'Кировская область', 'Kirov Oblast'],
  ['RU-KOS', 'Костромская область', 'Kostroma Oblast'],
  ['RU-KGN', 'Курганская область', 'Kurgan Oblast'],
  ['RU-KRS', 'Курская область', 'Kursk Oblast'],
  ['RU-LEN', 'Ленинградская область', 'Leningrad Oblast'],
  ['RU-LIP', 'Липецкая область', 'Lipetsk Oblast'],
  ['RU-MAG', 'Магаданская область', 'Magadan Oblast'],
  ['RU-MOS', 'Московская область', 'Moscow Oblast'],
  ['RU-MUR', 'Мурманская область', 'Murmansk Oblast'],
  ['RU-NIZ', 'Нижегородская область', 'Nizhny Novgorod Oblast'],
  ['RU-NGR', 'Новгородская область', 'Novgorod Oblast'],
  ['RU-NVS', 'Новосибирская область', 'Novosibirsk Oblast'],
  ['RU-OMS', 'Омская область', 'Omsk Oblast'],
  ['RU-ORE', 'Оренбургская область', 'Orenburg Oblast'],
  ['RU-ORL', 'Орловская область', 'Oryol Oblast'],
  ['RU-PNZ', 'Пензенская область', 'Penza Oblast'],
  ['RU-PSK', 'Псковская область', 'Pskov Oblast'],
  ['RU-ROS', 'Ростовская область', 'Rostov Oblast'],
  ['RU-RYA', 'Рязанская область', 'Ryazan Oblast'],
  ['RU-SAM', 'Самарская область', 'Samara Oblast'],
  ['RU-SAR', 'Саратовская область', 'Saratov Oblast'],
  ['RU-SAK', 'Сахалинская область', 'Sakhalin Oblast'],
  ['RU-SVE', 'Свердловская область', 'Sverdlovsk Oblast'],
  ['RU-SMO', 'Смоленская область', 'Smolensk Oblast'],
  ['RU-TAM', 'Тамбовская область', 'Tambov Oblast'],
  ['RU-TVE', 'Тверская область', 'Tver Oblast'],
  ['RU-TOM', 'Томская область', 'Tomsk Oblast'],
  ['RU-TUL', 'Тульская область', 'Tula Oblast'],
  ['RU-TYU', 'Тюменская область', 'Tyumen Oblast'],
  ['RU-ULY', 'Ульяновская область', 'Ulyanovsk Oblast'],
  ['RU-CHE', 'Челябинская область', 'Chelyabinsk Oblast'],
  ['RU-YAR', 'Ярославская область', 'Yaroslavl Oblast'],
  ['RU-MOW', 'Москва', 'Moscow'],
  ['RU-SPE', 'Санкт-Петербург', 'Saint Petersburg'],
  ['RU-YEV', 'Еврейская автономная область', 'Jewish Autonomous Oblast'],
  ['RU-NEN', 'Ненецкий автономный округ', 'Nenets Autonomous Okrug'],
  ['RU-KHM', 'Ханты-Мансийский автономный округ — Югра', 'Khanty-Mansi Autonomous Okrug — Yugra'],
  ['RU-CHU', 'Чукотский автономный округ', 'Chukotka Autonomous Okrug'],
  ['RU-YAN', 'Ямало-Ненецкий автономный округ', 'Yamalo-Nenets Autonomous Okrug'],
];

// Разряды и звания ЕВСК (решение Q-05: одно поле sportRank).
export const SPORT_RANKS: [code: string, ru: string, en: string, order: number][] = [
  ['YOUTH_3', '3 юношеский разряд', '3rd youth rank', 1],
  ['YOUTH_2', '2 юношеский разряд', '2nd youth rank', 2],
  ['YOUTH_1', '1 юношеский разряд', '1st youth rank', 3],
  ['SPORT_3', '3 спортивный разряд', '3rd sports rank', 4],
  ['SPORT_2', '2 спортивный разряд', '2nd sports rank', 5],
  ['SPORT_1', '1 спортивный разряд', '1st sports rank', 6],
  ['CMS', 'Кандидат в мастера спорта', 'Candidate Master of Sport', 7],
  ['MS', 'Мастер спорта России', 'Master of Sport of Russia', 8],
  ['MSIC', 'Мастер спорта России международного класса', 'Master of Sport, International Class', 9],
  ['HMS', 'Заслуженный мастер спорта России', 'Honoured Master of Sport of Russia', 10],
];

export const REFEREE_CATEGORIES: [code: string, ru: string, en: string, order: number][] = [
  ['YOUNG', 'Юный спортивный судья', 'Young sports referee', 1],
  ['CAT_3', 'Спортивный судья третьей категории', 'Sports referee, 3rd category', 2],
  ['CAT_2', 'Спортивный судья второй категории', 'Sports referee, 2nd category', 3],
  ['CAT_1', 'Спортивный судья первой категории', 'Sports referee, 1st category', 4],
  ['NATIONAL', 'Спортивный судья всероссийской категории', 'Sports referee, national category', 5],
  ['INTERNATIONAL', 'Судья международной категории', 'International referee', 6],
];

export const DISCIPLINES: [code: string, ru: string, en: string][] = [
  ['SPORT_SAMBO', 'Самбо', 'Sport sambo'],
  ['COMBAT_SAMBO', 'Боевое самбо', 'Combat sambo'],
  ['BEACH_SAMBO', 'Пляжное самбо', 'Beach sambo'],
  ['DEMO_SAMBO', 'Демонстрационное самбо', 'Demonstration sambo'],
];

const MB = 1024 * 1024;
const DOC_MIME = 'application/pdf,image/jpeg,image/png';

// Сроки хранения предварительные (DATABASE.md, 9), утверждаются с юристом.
export const DOCUMENT_TYPES: [code: string, ru: string, en: string, sensitivity: string, mime: string, max: number, days: number][] = [
  ['MEDICAL_CERTIFICATE', 'Медицинская справка о допуске', 'Medical clearance certificate', 'HEALTH', DOC_MIME, 10 * MB, 400],
  ['INSURANCE_POLICY', 'Полис страхования от несчастных случаев', 'Accident insurance policy', 'GENERAL', DOC_MIME, 10 * MB, 400],
  ['BIRTH_CERTIFICATE', 'Свидетельство о рождении', 'Birth certificate', 'IDENTITY', DOC_MIME, 10 * MB, 365],
  ['PASSPORT', 'Паспорт', 'Passport', 'IDENTITY', DOC_MIME, 10 * MB, 365],
  ['SPORT_RANK_ORDER', 'Приказ о присвоении разряда', 'Sports rank assignment order', 'GENERAL', DOC_MIME, 10 * MB, 730],
  ['CONSENT_SCAN', 'Скан согласия законного представителя', 'Guardian consent scan', 'GENERAL', DOC_MIME, 10 * MB, 1825],
  ['OTHER', 'Иной документ', 'Other document', 'GENERAL', DOC_MIME, 10 * MB, 365],
];
